### ISSUE TITLE
Some trouble getting this up and running

### ISSUE THREAD

**Issue by brocktopus** [Dex-Sinister/Fate.exe#1]
As an old MU*er and a lover of Fate, I've been really interested to see this system you wrote up in practice ... but I find myself struggling a bit with getting it working successfully. (For example, it seems to count stunts against the free # in the ruleset and the overall Refresh total in the reverse of what I expected.) I've tried tweaking parts of the code here and there, but without much luck (hence the lack of a PR).

Are you still working on this at all, by any chance?

**Comment by Dex-Sinister** [comment]
Hi Brock,

Thank you for the comment. Sorry for the delay in answering; I only just saw it now. Thank you for the feedback.

It has been a while since I last actively worked on this, but I'd be happy to see if I can tweak things and make it easier to set up. What are you most struggling with now, that needs adjustment? And what were you expecting from the stunt-counting, for this code to be the opposite?

**Comment by brocktopus** [comment]
Well, here are a couple examples. I'm making use of the Fate Core ruleset without modifications.

On a +sheet with no skills added, the 'Skill points' line reads:

    Skill points: 0/20

On a +sheet with skills maxed out, the same line reads:

    Skill points: 0/20

Or, with no stunts added (having a default Refresh of 3 and an expectation of 3 initial free stunts):

    Stunts until next refresh spent: 3

But if you add a stunt with a positive integer cost (e.g., +stunt/create Test Stunt=1), the result is the following:

    Stunts until next refresh spent: 4

...although I would have expected the number to drop to 2 rather than rise to 4.

**Comment by Dex-Sinister** [comment]
Aah, so that's the kind of opposite you'd meant. Yes, you need to give stunts a negative cost for them to subtract from your free-stunt allocations or your refresh.

I originally created this code for The Dresden Files RPG. In that version of Fate, there are some extras which cost multiple refresh, written as -cost (for instance, Inhuman Strength, costing two refresh, written as '-2'). Other extras can partially refund refresh, written as +cost (for instance, Human Form, which refunds one of the refresh spent on linked powers, written as '+1').

Thus, I designed the code to match what people would see in the book. This means that, yes, 'positive' cost increases your refresh or free stunt totals, while 'negative' cost subtracts from your resources. Sorry for the confusion.

**Comment by brocktopus** [comment]
Alright ... well, so much for that. Thanks for replying, at least.
